// Generated by CoffeeScript 1.12.6
(function() {
  var request;

  request = require('request');

  module.exports = function(options, maxRequests, interval) {
    if (interval == null) {
      interval = 1000;
    }
    return new Promise(function(resolve, reject) {
      var errorMessage, intervalID, makeRequest, requests, success;
      success = options.success || 200;
      delete options.success;
      errorMessage = options.errorMessage || 'No success.';
      delete options.errorMessage;
      makeRequest = function(intervalID) {
        return request(options, function(error, response, body) {
          if ((response != null ? response.statusCode : void 0) === success) {
            clearInterval(intervalID);
            return resolve(response);
          }
        });
      };
      requests = 0;
      intervalID = setInterval(function() {
        if (++requests === maxRequests) {
          clearInterval(intervalID);
          reject(errorMessage);
        }
        return makeRequest(intervalID);
      }, interval);
      return makeRequest();
    });
  };

}).call(this);
